### ISSUE TITLE
运行报错 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.dmj.service.DiscordService]: Factory method 'discordService' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder

### ISSUE THREAD

**Issue by japhet99** [ljjy1/discord-mj-java#2]
"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:59309,suspend=y,server=n -XX:TieredStopAtLevel=1 -noverify -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-Dmanagement.endpoints.jmx.exposure.include=*" -javaagent:C:\Users\29574\AppData\Local\JetBrains\IntelliJIdea2023.1\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_202\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_202\jre\lib\rt.jar;D:\桌面\otherProject\java-midjourney-api\japhet-mj-api\target\classes;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter-thymeleaf\2.5.14\spring-boot-starter-thymeleaf-2.5.14.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter\2.5.14\spring-boot-starter-2.5.14.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot\2.5.14\spring-boot-2.5.14.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-autoconfigure\2.5.14\spring-boot-autoconfigure-2.5.14.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter-logging\2.5.14\spring-boot-starter-logging-2.5.14.jar;D:\Software\java\maven\repository\ch\qos\logback\logback-classic\1.2.11\logback-classic-1.2.11.jar;D:\Software\java\maven\repository\ch\qos\logback\logback-core\1.2.11\logback-core-1.2.11.jar;D:\Software\java\maven\repository\org\apache\logging\log4j\log4j-to-slf4j\2.17.2\log4j-to-slf4j-2.17.2.jar;D:\Software\java\maven\repository\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;D:\Software\java\maven\repository\org\slf4j\jul-to-slf4j\1.7.36\jul-to-slf4j-1.7.36.jar;D:\Software\java\maven\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\Software\java\maven\repository\org\yaml\snakeyaml\1.28\snakeyaml-1.28.jar;D:\Software\java\maven\repository\org\thymeleaf\thymeleaf-spring5\3.0.15.RELEASE\thymeleaf-spring5-3.0.15.RELEASE.jar;D:\Software\java\maven\repository\org\thymeleaf\thymeleaf\3.0.15.RELEASE\thymeleaf-3.0.15.RELEASE.jar;D:\Software\java\maven\repository\org\attoparser\attoparser\2.0.5.RELEASE\attoparser-2.0.5.RELEASE.jar;D:\Software\java\maven\repository\org\unbescape\unbescape\1.1.6.RELEASE\unbescape-1.1.6.RELEASE.jar;D:\Software\java\maven\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\Software\java\maven\repository\org\thymeleaf\extras\thymeleaf-extras-java8time\3.0.4.RELEASE\thymeleaf-extras-java8time-3.0.4.RELEASE.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter-web\2.5.14\spring-boot-starter-web-2.5.14.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter-json\2.5.14\spring-boot-starter-json-2.5.14.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\core\jackson-databind\2.12.6.1\jackson-databind-2.12.6.1.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\core\jackson-core\2.12.6\jackson-core-2.12.6.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.12.6\jackson-datatype-jdk8-2.12.6.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.12.6\jackson-datatype-jsr310-2.12.6.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.12.6\jackson-module-parameter-names-2.12.6.jar;D:\Software\java\maven\repository\org\springframework\boot\spring-boot-starter-tomcat\2.5.14\spring-boot-starter-tomcat-2.5.14.jar;D:\Software\java\maven\repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.63\tomcat-embed-core-9.0.63.jar;D:\Software\java\maven\repository\org\apache\tomcat\embed\tomcat-embed-el\9.0.63\tomcat-embed-el-9.0.63.jar;D:\Software\java\maven\repository\org\apache\tomcat\embed\tomcat-embed-websocket\9.0.63\tomcat-embed-websocket-9.0.63.jar;D:\Software\java\maven\repository\org\springframework\spring-web\5.3.20\spring-web-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-beans\5.3.20\spring-beans-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-webmvc\5.3.20\spring-webmvc-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-aop\5.3.20\spring-aop-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-context\5.3.20\spring-context-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-expression\5.3.20\spring-expression-5.3.20.jar;D:\Software\java\maven\repository\org\projectlombok\lombok\1.18.24\lombok-1.18.24.jar;D:\Software\java\maven\repository\jakarta\xml\bind\jakarta.xml.bind-api\2.3.3\jakarta.xml.bind-api-2.3.3.jar;D:\Software\java\maven\repository\jakarta\activation\jakarta.activation-api\1.2.2\jakarta.activation-api-1.2.2.jar;D:\Software\java\maven\repository\org\springframework\spring-core\5.3.20\spring-core-5.3.20.jar;D:\Software\java\maven\repository\org\springframework\spring-jcl\5.3.20\spring-jcl-5.3.20.jar;D:\Software\java\maven\repository\com\alibaba\fastjson\1.2.83\fastjson-1.2.83.jar;D:\Software\java\maven\repository\cn\hutool\hutool-all\5.8.20\hutool-all-5.8.20.jar;D:\Software\java\maven\repository\com\github\xiaoymin\knife4j-openapi3-spring-boot-starter\4.1.0\knife4j-openapi3-spring-boot-starter-4.1.0.jar;D:\Software\java\maven\repository\com\github\xiaoymin\knife4j-core\4.1.0\knife4j-core-4.1.0.jar;D:\Software\java\maven\repository\com\github\xiaoymin\knife4j-openapi3-ui\4.1.0\knife4j-openapi3-ui-4.1.0.jar;D:\Software\java\maven\repository\org\springdoc\springdoc-openapi-common\1.6.15\springdoc-openapi-common-1.6.15.jar;D:\Software\java\maven\repository\io\swagger\core\v3\swagger-core\2.2.8\swagger-core-2.2.8.jar;D:\Software\java\maven\repository\org\apache\commons\commons-lang3\3.12.0\commons-lang3-3.12.0.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\dataformat\jackson-dataformat-yaml\2.12.6\jackson-dataformat-yaml-2.12.6.jar;D:\Software\java\maven\repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar;D:\Software\java\maven\repository\org\springdoc\springdoc-openapi-webflux-core\1.6.15\springdoc-openapi-webflux-core-1.6.15.jar;D:\Software\java\maven\repository\org\springframework\spring-webflux\5.3.20\spring-webflux-5.3.20.jar;D:\Software\java\maven\repository\io\projectreactor\reactor-core\3.4.18\reactor-core-3.4.18.jar;D:\Software\java\maven\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;D:\Software\java\maven\repository\org\springdoc\springdoc-openapi-webmvc-core\1.6.15\springdoc-openapi-webmvc-core-1.6.15.jar;D:\Software\java\maven\repository\org\springdoc\springdoc-openapi-ui\1.6.15\springdoc-openapi-ui-1.6.15.jar;D:\Software\java\maven\repository\org\webjars\swagger-ui\4.17.1\swagger-ui-4.17.1.jar;D:\Software\java\maven\repository\org\webjars\webjars-locator-core\0.46\webjars-locator-core-0.46.jar;D:\Software\java\maven\repository\io\github\classgraph\classgraph\4.8.149\classgraph-4.8.149.jar;D:\Software\java\maven\repository\io\swagger\core\v3\swagger-annotations\2.2.8\swagger-annotations-2.2.8.jar;D:\Software\java\maven\repository\io\swagger\core\v3\swagger-models\2.2.8\swagger-models-2.2.8.jar;D:\Software\java\maven\repository\com\fasterxml\jackson\core\jackson-annotations\2.12.6\jackson-annotations-2.12.6.jar;D:\桌面\otherProject\java-midjourney-api\japhet-mj-api\src\main\resources\lib\discord-mj-spring-boot-starter.jar;D:\Program Files\JetBrains\IntelliJ IDEA 2023.1.3\lib\idea_rt.jar" com.japhet.japhetmjapi.JaphetMjApiApplication
Connected to the target VM, address: '127.0.0.1:59309', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v2.5.14)

2023-10-20 18:01:14.098  INFO 12212 --- [           main] c.j.japhetmjapi.JaphetMjApiApplication   : Starting JaphetMjApiApplication using Java 1.8.0_202 on DESKTOP-JRIFDS0 with PID 12212 (D:\桌面\otherProject\java-midjourney-api\japhet-mj-api\target\classes started by Windows in D:\桌面\otherProject\java-midjourney-api\japhet-mj-api)
2023-10-20 18:01:14.100  INFO 12212 --- [           main] c.j.japhetmjapi.JaphetMjApiApplication   : No active profile set, falling back to 1 default profile: "default"
2023-10-20 18:01:14.810  INFO 12212 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 9527 (http)
2023-10-20 18:01:14.816  INFO 12212 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-10-20 18:01:14.817  INFO 12212 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.63]
2023-10-20 18:01:14.909  INFO 12212 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-10-20 18:01:14.909  INFO 12212 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 774 ms
2023-10-20 18:01:14.956  WARN 12212 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myController': Unsatisfied dependency expressed through field 'discordService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discordService' defined in class path resource [com/github/dmj/autoconfigure/DiscordPropertiesAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.dmj.service.DiscordService]: Factory method 'discordService' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
2023-10-20 18:01:14.959  INFO 12212 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-20 18:01:14.970  INFO 12212 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-10-20 18:01:14.986 ERROR 12212 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'myController': Unsatisfied dependency expressed through field 'discordService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discordService' defined in class path resource [com/github/dmj/autoconfigure/DiscordPropertiesAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.dmj.service.DiscordService]: Factory method 'discordService' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.14.jar:2.5.14]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:780) [spring-boot-2.5.14.jar:2.5.14]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:453) [spring-boot-2.5.14.jar:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:343) [spring-boot-2.5.14.jar:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1370) [spring-boot-2.5.14.jar:2.5.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1359) [spring-boot-2.5.14.jar:2.5.14]
	at com.japhet.japhetmjapi.JaphetMjApiApplication.main(JaphetMjApiApplication.java:10) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'discordService' defined in class path resource [com/github/dmj/autoconfigure/DiscordPropertiesAutoConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.dmj.service.DiscordService]: Factory method 'discordService' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:486) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:656) ~[spring-beans-5.3.20.jar:5.3.20]
	... 20 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.dmj.service.DiscordService]: Factory method 'discordService' threw exception; nested exception is java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.20.jar:5.3.20]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.20.jar:5.3.20]
	... 33 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at com.github.dmj.service.api.DiscordApi.<init>(DiscordApi.java:71) ~[discord-mj-spring-boot-starter.jar:na]
	at com.github.dmj.autoconfigure.DiscordPropertiesAutoConfig.discordService(DiscordPropertiesAutoConfig.java:101) ~[discord-mj-spring-boot-starter.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.20.jar:5.3.20]
	... 34 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_202]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_202]
	... 41 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:59309', transport: 'socket'

Process finished with exit code 1

**Comment by ljjy1** [comment]
@japhet99 你的com.google.guava包应该有依赖冲突 有两个版本的 你看下要不就排除掉中间件里面的 要不你在你的项目就不要引入 你可以看下我写的测试项目

**Comment by japhet99** [comment]
大佬，我运行你那个test项目也报这个错，然后我自己创建了一个项目，把代码贴过去，还是报一样的错，请问是不是jdk或者其他什么版本不同造成的？

我jdk1.8  / 17 都试过，idea运行都报错，但是，我打成jar包就能正常启动（jdk17，我新建的项目）,所以是不是哪个地方还需要配置？

**Comment by japhet99** [comment]
> @japhet99你的com.google.guava包应该有依赖冲突有两个版本的你看下要不要就修复掉中间件里面的要不是你在你的项目就不要引入你可以看下我写的测试项目

我是新建的项目，没有引入其他maven 包，我引入了你的包是我重新打的jar包，然后是本地引入的

**Comment by japhet99** [comment]
解决这个报错了，是因为引入重复了,删除<dependencyManagement>，贴一下我pom.xml里面的代码，改成这样就好了，包括你那个test项目的pom.xml

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.dmj</groupId>
    <artifactId>discord-mj-java-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <fastjson.version>1.2.83</fastjson.version>
        <hutool.version>5.8.20</hutool.version>
        <knife4j.openapi.version>4.1.0</knife4j.openapi.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-spring-boot-starter</artifactId>
            <version>${knife4j.openapi.version}</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-support</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.dmj</groupId>
            <artifactId>discord-mj-spring-boot-starter</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>

</project>
